plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sonora.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.sonora.app"
        minSdk 24
        targetSdk 32
        versionCode 12
        versionName "2.1"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
